configuration: Debug
platform: Any CPU
image: Visual Studio 2017
install:
- git submodule update --init --recursive
- ps: |
    function gitVersion(){
      $majorVersion = 3;
      $minorVersion = 0;
      $revision = 0;
      $baseCommitHash = "d779383cb85003d6dabeb976f0845631e07bf463";
      if ($env:APPVEYOR_REPO_BRANCH -ne 'master') {
        $branch = "-$env:APPVEYOR_REPO_BRANCH";
      } else {
        $branch = "";
      }

      $build = git rev-list --count "$baseCommitHash..HEAD";

      $newVersion="$majorVersion.$minorVersion.$revision.$build";
      
      write-host "Update appveyor build version to:$newVersion"
      $env:ilspy_version_number=$newVersion
      $env:appveyor_build_version="$newVersion$branch"
      appveyor UpdateBuild -Version "$newVersion$branch"
    }
    gitVersion
before_build:
- nuget restore ILSpy.sln
build_script:
- msbuild ILSpy.sln /v:minimal /p:ResolveNuGetPackages=false "/logger:%ProgramFiles%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
after_build:
- 7z a ILSpy_%APPVEYOR_REPO_BRANCH%_%ILSPY_VERSION_NUMBER%_Binaries.zip %APPVEYOR_BUILD_FOLDER%\ILSpy\bin\Debug\*.dll %APPVEYOR_BUILD_FOLDER%\ILSpy\bin\Debug\*.exe %APPVEYOR_BUILD_FOLDER%\ILSpy\bin\Debug\*.config
test:
  assemblies:
    - 'ICSharpCode.Decompiler.Tests\bin\Debug\net461\ICSharpCode.Decompiler.Tests.exe'
    - 'ILSpy.BamlDecompiler.Tests\bin\Debug\net461\ILSpy.BamlDecompiler.Tests.dll'
after_test:
- python BuildTools\tidy.py
artifacts:
  - path: ILSpy_%APPVEYOR_REPO_BRANCH%_%ILSPY_VERSION_NUMBER%_Binaries.zip
    name: ILSpy binaries test