platform: Any CPU
configuration:
- Debug
- Release
image: Visual Studio 2017
install:
- git submodule update --init --recursive
- ps: .\BuildTools\appveyor-ilspycmd-install.ps1
dotnet_csproj:
  patch: true
  file: 'ICSharpCode.Decompiler.Console\ICSharpCode.Decompiler.Console.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- nuget restore ICSharpCode.Decompiler.Console.sln
build_script:
- msbuild ICSharpCode.Decompiler.Console.sln /v:minimal /p:ResolveNuGetPackages=false "/logger:%ProgramFiles%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
after_test:
- python BuildTools\tidy.py