version: 1.0.{build}
configuration: Debug
platform: Any CPU
install:
- git submodule update --init --recursive
- git checkout https://github.com/icsharpcode/ILSpy-tests
before_build:
- nuget restore ILSpy.sln
build:
  project: ILSpy.sln
  parallel: true
  verbosity: minimal
after_test:
- python BuildTools\tidy.py
