version: 1.0.{build}
configuration: Debug
platform: Any CPU
image: Visual Studio 2017
install:
- git submodule update --init --recursive
before_build:
- nuget restore ILSpy.sln
build_script:
- msbuild ILSpy.sln /v:minimal /p:ResolveNuGetPackages=false /t:BeforeBuild,Build "/logger:%ProgramFiles%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
test:
  assemblies:
    - 'ICSharpCode.Decompiler.Tests\bin\Debug\net461\ICSharpCode.Decompiler.Tests.exe'
    - 'ILSpy.BamlDecompiler.Tests\bin\Debug\net461\ILSpy.BamlDecompiler.Tests.dll'
after_test:
- python BuildTools\tidy.py
